### ISSUE TITLE
Reducers Exercise showing solution

### ISSUE THREAD

**Issue by dtauer** [stevekinney/react-and-typescript-projects#7]
Hey Steve - The CodeSandbox for the Reducers exercise lesson already has most of the solution in it:

https://codesandbox.io/s/incident-counter-reducer-base-cgsin?file=/src/Application.tsx

In the course, the code in that sandbox should just be the basic counter.

**Comment by stevekinney** [comment]
Thanks! I reset the code to what's in `examples/20-incident-counter-reducer-exercise`, which I believe is correct.
